import Footer from "@/components/partials/Footer";
import Header from "@/components/partials/Header";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import PageRender from "./pageRender";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Lemon Hive Task",
  description: "Generated by create lemon hive",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <PageRender>{children}</PageRender>
        <Footer />
      </body>
    </html>
  );
}
